### ISSUE TITLE
Game won't start with this mod

### ISSUE THREAD

**Issue by AthinCZ** [DasBlackfur/ZombieConversion#3]
The game crashes immediately after starting, not even the loading screen is displayed.

Tested on a fresh instance of Minecraft 1.19.2 with:
Fabric - 0.14.13 - 1.19.2
Fabric API - 0.73.0 - 1.19.2
Zombie Conversion - 1.0.0 - 1.19.2

Attached log file: [latest.log](https://github.com/DasBlackfur/ZombieConversion/files/10475601/latest.log)

I haven't tested it on Minecraft 1.19.3, as not all the mods I use have been updated to 1.19.3 yet, so I'm still playing on 1.19.2.

**Comment by DasBlackfur** [comment]
I know this is over a year ago, but I fixed it
